#!/bin/bash

. .install
. .functions

I_DOCKER_REPO="https://download.docker.com/linux/centos/docker-ce.repo"
I_DOCKER='run=i_docker_'${I_D}'check=i_docker_exist'
I_DOCKER_VER="18.03.0"

I_DOCKER_ETC=/etc/docker
I_DOCKER_DAEMON=../docker/daemon.json

usage() {
  echo "Usage: $0 [-h] [-p proxy] ${I_ALL}|all"
  echo ""
  echo "  -h|--help,   print usage"
  echo "  -p|--proxy,  proxy server"
  echo ""
  exit 0
}

while [[ $# -gt 0 ]]; do
o=$1
case "$o" in
  -h|--help)  usage ;;
  -p|--proxy) G_PROXY="$2"; shift ;;
  *) G_RUNS="$o,$G_RUNS" ;;
esac
shift
done

G_RUNS=${G_RUNS::-1}
[ -z "$G_RUNS" ] && usage
[ "$G_RUNS" = "all" ] && G_RUNS="$I_ALL"

i_common() {
  sudo yum install -y epel-release yum-utils
  sudo yum groupinstall -y 'Development Tools'
  sudo yum install -y sudo nodejs vsftpd git \
    clang cmake ctags cscope ssh screen \
    htop iotop wget zlib-devel ncurses-devel \
    openssl-devel python-devel python3-devel \
    ruby ruby-devel lua lua-devel luajit tcl-devel \
    perl perl-devel perl-ExtUtils-ParseXS \
    perl-ExtUtils-XSpp perl-ExtUtils-CBuilder \
    perl-ExtUtils-Embed php php-common
}

i_docker_exist() {
  which docker > /dev/null 2>&1
  local ret=$?
  [ $ret -eq 0 ] && echo 1
  [ $ret -ne 0 ] && echo 0
}

i_docker_() {
  sudo yum install -y device-mapper-persistent-data lvm2
  sudo wget $I_DOCKER_REPO -O /etc/yum.repos.d/docker-ce.repo
  sudo yum install -y docker-ce-${I_DOCKER_VER}.ce
  sudo mkdir -p "$I_DOCKER_ETC"
  f_copy "$I_DOCKER_DAEMON" "$I_DOCKER_ETC/daemon.json"
  sudo systemctl start docker
}

i_pre
i_common
IFS=',' read -ra runs <<< "$G_RUNS"
for i in ${runs[@]}; do
  _run=I_${i^^}
  if [[ -z "${!_run}" ]]; then
    echo "[$i] can't find, please choose following ones to install, [$I_ALL]"
    exit 1
  fi
done
f_runs ${runs[@]}
i_post
